const sample = `주문번호\t상품명\t수량\t보내는분\t받는분\t연락처\t우편번호\t배송지
20260812-001\t프리미엄 감사 선물세트\t1\t보내는분 예시\t받는분 예시\t010-0000-0000\t00000\t서울특별시 예시구 예시로 1
20260812-002\t수제 쿠키 답례품 10개입\t2\t스토어 예시\t수취인 예시\t010-0000-0000\t00000\t부산광역시 예시구 예시길 2`;
let orders=[]; const $=id=>document.getElementById(id);
const fields={order:['주문번호','주문 번호'],product:['상품명','상품 이름','상품'],quantity:['수량'],sender:['보내는분','보내는 분','발신자'],recipient:['받는분','받는 분','수취인'],phone:['연락처','전화번호','휴대폰'],postcode:['우편번호'],address:['배송지','주소']};
const clean=v=>String(v??'').trim();
const indexOf=(headers,names)=>headers.findIndex(h=>names.map(n=>n.replaceAll(' ','').toLowerCase()).includes(clean(h).replaceAll(' ','').toLowerCase()));
function parse(raw){const lines=raw.trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const sep=lines[0].includes('\t')?'\t':lines[0].includes(',')?',':'|';const data=lines.map(line=>line.split(sep).map(clean));const headers=data[0];const header=Object.values(fields).some(names=>indexOf(headers,names)>=0);const i={};Object.entries(fields).forEach(([key,n],fallback)=>i[key]=header?indexOf(headers,n):fallback);return data.slice(header?1:0).map((row,n)=>({id:`manual-${Date.now()}-${n}`,order:row[i.order]||`주문 ${n+1}`,product:row[i.product]||'상품명 미입력',quantity:row[i.quantity]||'1',sender:row[i.sender]||'-',recipient:row[i.recipient]||'-',phone:row[i.phone]||'-',postcode:row[i.postcode]||'-',address:row[i.address]||'-'})).filter(o=>o.product!=='상품명 미입력'||o.recipient!=='-');}
const esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=o=>`[${o.order}]\n상품: ${o.product} (${o.quantity}개)\n보내는분: ${o.sender}\n받는분: ${o.recipient}\n연락처: ${o.phone}\n배송지: (${o.postcode}) ${o.address}`;
function render(){const q=$('searchInput').value.toLowerCase();const visible=orders.filter(o=>[o.product,o.sender,o.recipient,o.address].join(' ').toLowerCase().includes(q));$('orderCount').textContent=`${orders.length}건`;$('emptyState').classList.toggle('hidden',!!orders.length);$('tableWrap').classList.toggle('hidden',!orders.length);$('orderRows').innerHTML=visible.map(o=>`<tr><td><span class="order-number">${esc(o.order)}</span><span class="product">${esc(o.product)}</span><span class="quantity">${esc(o.quantity)}개</span></td><td class="message"><div><em>보내는분</em>${esc(o.sender)}</div><div><em>받는분</em>${esc(o.recipient)}</div></td><td class="address"><strong>${esc(o.recipient)}</strong><small>${esc(o.phone)}</small><p><small>${esc(o.postcode)}</small> ${esc(o.address)}</p></td><td><button class="row-copy" data-id="${esc(o.id)}">복사</button></td></tr>`).join('')||'<tr><td colspan="4">검색 결과가 없습니다.</td></tr>';}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1900)}
async function copy(value){try{await navigator.clipboard.writeText(value);toast('클립보드에 복사했습니다.')}catch{toast('브라우저의 복사 권한을 허용해 주세요.')}}
async function fetchOrders(){const button=$('apiButton'),status=$('apiStatus');button.disabled=true;button.textContent='주문 불러오는 중…';status.textContent='네이버 주문을 안전하게 조회하고 있습니다.';status.className='status loading';try{const res=await fetch('/api/orders');const body=await res.json();if(!res.ok)throw new Error(body.message||'주문을 불러오지 못했습니다.');orders=body.orders||[];render();status.textContent=`최근 24시간 기준 ${orders.length}건을 불러왔습니다.`;status.className='status';toast(`${orders.length}건의 주문을 불러왔습니다.`);document.querySelector('.orders').scrollIntoView({behavior:'smooth'});}catch(err){status.textContent=err.message;status.className='status loading';toast('API 연결 설정을 확인해 주세요.');}finally{button.disabled=false;button.textContent='스마트스토어에서 불러오기';}}
$('apiButton').addEventListener('click',fetchOrders);$('sampleButton').addEventListener('click',()=>{$('importText').value=sample;$('importHint').textContent='예시 데이터가 입력되었습니다.'});$('parseButton').addEventListener('click',()=>{const result=parse($('importText').value);if(!result.length)return toast('붙여넣은 주문 정보를 확인해 주세요.');orders=result;render();$('importHint').textContent=`${orders.length}건을 정리했습니다.`});$('searchInput').addEventListener('input',render);$('clearButton').addEventListener('click',()=>{orders=[];$('importText').value='';render();toast('주문 목록을 비웠습니다.')});$('copyButton').addEventListener('click',()=>orders.length?copy(orders.map(text).join('\n\n')):toast('복사할 주문이 없습니다.'));$('orderRows').addEventListener('click',e=>{const o=orders.find(item=>item.id===e.target.dataset.id);if(o)copy(text(o));});$('downloadButton').addEventListener('click',()=>{if(!orders.length)return toast('저장할 주문이 없습니다.');const columns=['주문번호','상품명','수량','보내는분','받는분','연락처','우편번호','배송지'];const rows=orders.map(o=>[o.order,o.product,o.quantity,o.sender,o.recipient,o.phone,o.postcode,o.address]);const csv=[columns,...rows].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='주문정리.csv';a.click();URL.revokeObjectURL(a.href);});render();
